cask_args appdir: "/Applications"

tap "homebrew/bundle"

# Casks
cask "1password"
cask "vagrant"
cask "virtualbox"
cask "tunnelblick"
cask "wireshark"
cask "postman"
cask "visual-studio-code"
cask "keybase"
cask "java"
cask "zoom"
cask "jetbrains-toolbox"
cask "sublime-merge"
cask "sublime-text"
cask "mongodb-compass-community"
cask "fantastical"
cask "keepassxc"
cask "spotify"
cask "cyberduck"


# CLI Apps
brew "cmake"
brew "go"
brew "rust"
brew "tmux"
brew "python"
brew "python3"
brew "iperf3"
brew "node"
brew "htop"
brew "wget"
brew "gnupg"
brew "gpg2"
brew "ykman"
brew "ctags"
brew "pinentry-mac"
brew "kubectl"
